version: "3.7"
services:
  gatsby-my-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby-my-site
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    environment:
      - NODE_ENV=development